SKILLS = [  # noqa
    "Ceramics designer",
    "Chiropractor",
    "Community pharmacist",
    "Music therapist",
    "Chief Financial Officer",
    "Engineer, agricultural",
    "Commercial/residential surveyor",
    "Nurse, learning disability",
    "Ranger/warden",
    "Therapist, horticultural",
    "Risk manager",
    "Copy",
    "Mechanical engineer",
    "Psychotherapist, dance movement",
    "Geographical information systems officer",
    "Acupuncturist",
    "Dancer",
    "Occupational therapist",
    "Engineer, civil (consulting)",
    "IT consultant",
    "Careers information officer",
    "Physiotherapist",
    "Special educational needs teacher",
    "Graphic designer",
    "Scientist, research (medical)",
    "Primary school teacher",
    "Quality manager",
    "Accountant, chartered certified",
    "Interpreter",
    "Public affairs consultant",
    "Secretary/administrator",
    "Civil Service fast streamer",
    "Designer, graphic",
    "Engineer, aeronautical",
    "Pensions consultant",
    "Pharmacist, hospital",
    "Presenter, broadcasting",
    "Farm manager",
    "Media buyer",
    "Public relations officer",
    "Editor, film/video",
    "Mental health nurse",
    "Youth worker",
    "Trading standards officer",
    "Chemist, analytical",
    "Jewellery designer",
    "Water engineer",
    "Dietitian",
    "Psychologist, clinical",
    "Air broker",
    "Land/geomatics surveyor",
    "Lighting technician, broadcasting/film/video",
    "Podiatrist",
    "Air traffic controller",
    "Horticultural therapist",
    "Writer",
    "Chiropodist",
    "Energy engineer",
    "Marine scientist",
    "Agricultural consultant",
    "Biomedical scientist",
    "Production manager",
    "Geneticist, molecular",
    "Soil scientist",
    "Amenity horticulturist",
    "Fashion designer",
    "Programmer, applications",
    "Colour technologist",
    "Engineer, technical sales",
    "Financial trader",
    "Call centre manager",
    "Systems analyst",
    "Tourist information centre manager",
    "Transport planner",
    "Engineer, control and instrumentation",
    "Armed forces logistics/support/administrative officer",
    "Clinical cytogeneticist",
    "Engineer, water",
    "Learning mentor",
    "Psychologist, forensic",
    "Management consultant",
    "Chartered loss adjuster",
    "Historic buildings inspector/conservation officer",
    "Publishing copy",
    "Forest/woodland manager",
    "Pilot, airline",
    "Development worker, international aid",
    "Neurosurgeon",
    "Research scientist (maths)",
    "Film/video editor",
    "Systems developer",
    "Data processing manager",
    "Forensic scientist",
    "Psychologist, sport and exercise",
    "Surveyor, building control",
    "Airline pilot",
    "Building services engineer",
    "Editorial assistant",
    "Production assistant, television",
    "Insurance broker",
    "Marketing executive",
    "Radio broadcast assistant",
    "Health service manager",
    "Learning disability nurse",
    "Surgeon",
    "Race relations officer",
    "Teacher, secondary school",
    "Careers adviser",
    "Engineer, electronics",
    "Information systems manager",
    "Risk analyst",
    "Estate agent",
    "Production engineer",
    "Trade mark attorney",
    "Warden/ranger",
    "Armed forces technical officer",
    "Conservation officer, nature",
    "Merchandiser, retail",
    "Designer, furniture",
    "Programmer, systems",
    "Structural engineer",
    "Conservator, museum/gallery",
    "Editor, commissioning",
    "Dance movement psychotherapist",
    "Librarian, academic",
    "Naval architect",
    "Psychotherapist, child",
    "Recycling officer",
    "Television production assistant",
    "Immunologist",
    "Medical illustrator",
    "Paramedic",
    "Administrator, arts",
    "Broadcast presenter",
    "Surveyor, hydrographic",
    "Firefighter",
    "Product manager",
    "Catering manager",
    "Mudlogger",
    "Engineer, maintenance (IT)",
    "Actuary",
    "Secretary, company",
    "Industrial buyer",
    "Charity fundraiser",
    "Animator",
    "Occupational psychologist",
    "Bonds trader",
    "Forensic psychologist",
    "Senior tax professional/tax inspector",
    "Diplomatic Services operational officer",
    "Health and safety adviser",
    "Insurance claims handler",
    "Fine artist",
    "Administrator, local government",
    "Chartered accountant",
    "Chartered management accountant",
    "Customer service manager",
    "Administrator",
    "Engineer, petroleum",
    "Journalist, broadcasting",
    "Housing manager/officer",
    "Hydrographic surveyor",
    "Ophthalmologist",
    "Community arts worker",
    "Intelligence analyst",
    "Journalist, newspaper",
    "Air cabin crew",
    "Producer, television/film/video",
    "Commercial art gallery manager",
    "Photographer",
    "Proofreader",
    "Trade union research officer"
]
